### ISSUE TITLE
Ложное оповещение

### ISSUE THREAD

**Issue by dronelektron** [ppalex7/SourceComms#10]
Когда даю гаг игроку (админу с низкой имункой и без кастом2 флага), то если он пишет !ungag @me и в итоге я вижу сообещние, что с него сняло гаг, хотя на самом деле ничего ен сняло, просто показало визуально ложное сообщение...

**Comment by ppalex7** [comment]
Кажется, что починил в 7c682ff0705e5aecc37231a6f0b4793ceabd40fd Проверь пожалуйста
