### ISSUE TITLE
sql error in sourcebans log

### ISSUE THREAD

**Issue by Nomy** [ppalex7/SourceComms#5]
Error: 
[code]You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) as gag_count,
            UNIX_TIMESTAMP() as c_time
            FROM sb_comms AS CO FORCE INDE' at line 5<br /><br />Query: SELECT CO.bid ban_id, CO.type, CO.authid, CO.name player_name, created ban_created, ends ban_ends, length ban_length, reason ban_reason, CO.ureason unban_reason, CO.aid, AD.gid AS gid, adminIp, CO.sid ban_server, RemovedOn, RemovedBy, RemoveType row_type,
            SE.ip server_ip, AD.user admin_name, MO.icon as mod_icon,
            CAST(MID(CO.authid, 9, 1) AS UNSIGNED) + CAST('76561197960265728' AS UNSIGNED) + CAST(MID(CO.authid, 11, 10) \* 2 AS UNSIGNED) AS community_id,
            (SELECT count(_) FROM sb_comms as BH WHERE (BH.authid = CO.authid AND BH.authid != '' AND BH.authid IS NOT NULL AND BH.type = 1)) as mute_count,
            (SELECT count(_) FROM sb_comms as BH WHERE (BH.authid = CO.authid AND BH.authid != '' AND BH.authid IS NOT NULL AND )) as gag_count,
            UNIX_TIMESTAMP() as c_time
            FROM sb_comms AS CO FORCE INDEX (created)
            LEFT JOIN sb_servers AS SE ON SE.sid = CO.sid
            LEFT JOIN sb_mods AS MO on SE.modid = MO.mid
            LEFT JOIN sb_admins AS AD ON CO.aid = AD.aid

```
  WHERE CO.aid='64'
```

   ORDER BY CO.created DESC
   LIMIT 0,60[/code]

Function: 
/home/public_html/sourcebans/includes/adodb/adodb.inc.php - 916<br />/home/public_html/sourcebans/includes/adodb/adodb.inc.php - 872<br />/home/public_html/sourcebans/pages/page.commslist.php - 367<br />/home/public_html/sourcebans/includes/page-builder.php - 105<br />/home/public_html/sourcebans/index.php - 23<br />

Query: p=commslist&advSearch=64&advType=admin

MySQL client version: 5.5.29

**Comment by ppalex7** [comment]
I am sorry, I made this mistake at one of the previous updates. I will fix it at the next day.

**Comment by ppalex7** [comment]
Fixed! Please update your [page.commslist.php](https://github.com/d-ai/SourceComms/raw/master/web_upload/pages/page.commslist.php) and [page_comms.tpl](https://raw.github.com/d-ai/SourceComms/master/web_upload/themes/default/page_comms.tpl)

Also, please run following sql queries:
ALTER TABLE sb_comms DROP INDEX reason;
ALTER TABLE sb_comms DROP INDEX authid_2;
ALTER TABLE sb_comms DROP INDEX name;

**Comment by Nomy** [comment]
Thanks Alex! :+1:
