### ISSUE TITLE
Undefined class constant

### ISSUE THREAD

**Issue by WildCard65** [ppalex7/SourceComms#53]
PHP Fatal error:  Undefined class constant 'STEAM_PATTERN' in /home/flexcraft/site/bans/application/plugins/SourceComms/models/Comms.php on line 157, referer: https://wildcard65gaming.bounceme.net/flexcraft/bans/index.php/admin
downloaded zip develop branch just today(today = day that this issue is posted)

**Comment by ppalex7** [comment]
This problem caused by the [recent sourcebans changes](https://github.com/GameConnect/SourceBans/commit/7b145fbc1ef7e61060a39b399cd493057509c2a3). I will fix them soon

**Comment by ppalex7** [comment]
Fixed

**Comment by WildCard65** [comment]
Yeap, fix works, good job
