### ISSUE TITLE
Nothing critical or important but may be useful.

### ISSUE THREAD

**Issue by WildCard65** [ppalex7/SourceComms#55]
Not sure if these are current planned for the sb2.0 rewrite of the sourcecomms webpanel but I would like them added(when you feel like adding them):
1) A button to remove blocks. --Thx d-ai
2) Last comms added section on dashboard.

**Comment by ppalex7** [comment]
remove action - in plans,
last comms - I also have an idea, but need to check the ability to embed blocks on this page

**Comment by ppalex7** [comment]
Checkout "remove" link

**Comment by WildCard65** [comment]
Deleting comms works

**Comment by ppalex7** [comment]
could you give the image as you imagine sourcecomms section on dashboard?

**Comment by WildCard65** [comment]
In the section where sourcebans adds it, you may want to make a file edit of sourcebans itself to add if it was from sourcebans(So like when a comms is added, it'll be: Type Game Date/Time Name)
Edit: Just realized delete comms doesn't auto ungag ppl

**Comment by ppalex7** [comment]
i know. There are no "online" functionality at this moment like: "gag", "ungag", deleting punishment. I'm waiting sourcebans, when i can look at the same functionality as an example for sourcecomms.

**Comment by ppalex7** [comment]
comms section at dashboard will looks very strange if it will be a single column under the bans.

Oh, idea, one column for gags and one (under blocks) - for mutes. What do you think?

**Comment by WildCard65** [comment]
Sounds cool.
Also this was totally not added to original post, didn't come to me till after I posted it(and after you started working on this), but it may get a little cluttered with how silences are added(2 seperate entries), so why not add a silence type(with a picture that's a hybrid of mute and gag's pic)

**Comment by ppalex7** [comment]
Something like this
![2014-02-23 20 08 49](https://f.cloud.github.com/assets/3440832/2240702/df76cda6-9ca4-11e3-8cca-354cdc044601.png)

**Comment by WildCard65** [comment]
ya
