### ISSUE TITLE
Неправильный значок на SourceBans при блокировке в игре

### ISSUE THREAD

**Issue by BlagoYar** [ppalex7/SourceComms#68]
Не знаю от чего зависит, так и не понял, но ...
Если игрок получает мут или бан в игре (сервере), то на сайте SourceBans отображается иконка, как-будто он получил его на сайте. То бишь чёрно-красная иконка SB, а не иконка CS: S
Но это не всегда, заметил только один раз, что это случилось, когда редактировал файлы конфигураций (перевод делал и т.д.)

Можно ли это как-то поправить?

ПС. Когда в первый раз заметил, думал потом решу проблему, но он исчезла сама (или я не поняв это решил :) )
У меня установлен SourceBans++. Возможно, что это он глючит?

**Comment by ppalex7** [comment]
думаю, что это были какие-то проблемы с определением игры на сервере со стороны Sourcebans. со стороны моего мода тут ничем не помочь - для иконок используются данные sourcebans плагина (при выдаче мьюта) и движка sourcebans при отображении

**Comment by BlagoYar** [comment]
Спасибо за ответ
